# Generated by Django 4.2.3 on 2023-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='متن توصیف')),
                ('completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
