# Generated by Django 4.2.3 on 2023-07-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_itemtodo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtodo',
            name='user',
        ),
    ]
