# Generated by Django 4.2.3 on 2023-07-17 15:44

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_itemtodo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtodo',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='عنوان در url'),
        ),
    ]
