# Generated by Django 4.2.3 on 2023-07-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(max_length=100, null=True, verbose_name='کد فعالسازی ایمیل'),
        ),
    ]
